openapi: 3.1.0
info:
  title: Wallet Exhibition API
  description: Wallet Exhibition API Documentation
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/v1/api'
paths:
  /users/register:
    post:
      summary: for use registration
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"
      responses:
        "201":
          description: successful registration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /users/login:
    post:
      summary: for use login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    UserRegistration:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
            token:
              type: string
